image: bradrydzewski/go:1.5
git:
  path: github.com/drone/drone
env:
  - GOROOT=/usr/local/go
  - PATH=$PATH:$GOROOT/bin:$GOPATH/bin

script:
  - go get golang.org/x/tools/cmd/cover
  - go get golang.org/x/tools/cmd/vet
  - go get -u github.com/jteeuwen/go-bindata/...
  - make bindata deps
  - go run make.go build
  - go run make.go vet test
  - make dist

notify:
  email:
    recipients:
      - brad@drone.io

publish:
  s3:
    acl: public-read
    region: us-east-1
    bucket: downloads.drone.io
    access_key: $$AWS_KEY
    secret_key: $$AWS_SECRET
    source: dist/drone.deb
    target: $DRONE_BRANCH/
    when:
      owner: drone

# new .drone.yml syntax

clone:
  path: github.com/drone/drone

build:
  image: golang:1.5.0
  commands:
    - export GOPATH=/drone
    - export PATH=$PATH:$GOPATH/bin
    - go get -u github.com/jteeuwen/go-bindata/...
    - make deps
    - make
    - make test
    - make dist

compose:
  database:
    image: mysql:5.5
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=test
