workspace:
  base: /go
  path: src/github.com/drone/drone

pipeline:

  test:
    image: golang:1.8
    commands:
      - make deps gen
      - make test test_postgres test_mysql

  dist:
    image: golang:1.8
    commands:
      - ./ci.sh
      - ./dist.sh
    secrets: [ ssh_key ]
    when:
      event: push

  archive:
    image: plugins/s3
    acl: public-read
    bucket: downloads.drone.io
    source: release/**/*.*
    target: /0.6.0/
    secrets: [ aws_access_key_id, aws_secret_access_key ]
    when:
      event: push
      branch: master

  publish_docker:
    image: plugins/docker
    repo: drone/drone
    secrets: [ docker_username, docker_password ]
    tag: [ latest, 0.6, 0.6.0 ]
    when:
      branch: master
      event: push

  publish_cli:
    image: plugins/github-release
    files: release/*/*/drone.tar.gz
    checksum: [ sha256 ]
    when:
      event: tag

  notify:
    image: plugins/gitter
    secrets: [ gitter_webhook ]
    when:
      status: [ success, failure ]

services:
  postgres:
    image: postgres:9.4.5
    environment:
      - POSTGRES_USER=postgres
  mysql:
    image: mysql:5.6.27
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
