image: go1.3
git:
  path: github.com/drone/drone
env:
  - GOROOT=/usr/local/go
  - PATH=$PATH:$GOROOT/bin:$GOPATH/bin
script:
  - sudo apt-get -y install zip libsqlite3-dev sqlite3 rpm 1> /dev/null 2> /dev/null
  - gem install fpm
  - rbenv rehash
  - make deps
  - make test
  - make test_postgres
  - make test_mysql
  - make packages
services:
  - postgres
  - mysql
notify:
  gitter:
    room_id: 76f5e5ec935c5b40259a
    token: $$GITTER_KEY
    on_started: false
    on_success: false
    on_failure: false

publish:
  s3:
    acl: public-read
    region: us-east-1
    bucket: downloads.drone.io
    access_key: $$AWS_KEY
    secret_key: $$AWS_SECRET
    source: packaging/output/
    target: $DRONE_BRANCH/
    recursive: true
