image: go1.3
git:
  path: github.com/drone/drone
env:
  - GOROOT=/usr/local/go
  - PATH=$PATH:$GOROOT/bin:$GOPATH/bin
script:
  - go get -u github.com/jteeuwen/go-bindata/...
  - make bindata deps
  - make build
  - make test

notify:
  email:
    recipients:
      - brad@drone.io
