image: bradrydzewski/go:1.3
git:
  path: github.com/drone/drone
env:
  - GOROOT=/usr/local/go
  - PATH=$PATH:$GOROOT/bin:$GOPATH/bin
script:
  - sudo add-apt-repository ppa:git-core/ppa 1> /dev/null 2> /dev/null
  - sudo apt-get update 1> /dev/null 2> /dev/null
  - sudo apt-get -y install git zip libsqlite3-dev sqlite3 rpm dpkg 1> /dev/null 2> /dev/null
  - gem install fpm
  - rbenv rehash
  - make deps
  - make test
<<<<<<< HEAD
  - make test_postgres
=======
  #- make test_postgres
  - make test_mysql
>>>>>>> de64629... don't test postgres
  - make packages
services:
  - postgres
publish:
  s3:
    acl: public-read
    region: us-east-1
    bucket: downloads.drone.io
    access_key: $$AWS_KEY
    secret_key: $$AWS_SECRET
    source: packaging/output/
    target: $DRONE_BRANCH/
    recursive: true
    when:
      owner: drone

# new build script for 0.4 branch

build:
  image: golang:1.4.2
  environment:
    - GOPATH=/drone
  commands:
    - apt-get update 1> /dev/null 2> /dev/null
    - apt-get -y install libsqlite3-dev sqlite3 1> /dev/null 2> /dev/null
    - go get golang.org/x/tools/cmd/vet
    - go get golang.org/x/tools/cmd/cover
    - make deps
    - make test
