image: bradrydzewski/go:1.3
git:
  path: github.com/drone/drone
env:
  - GOROOT=/usr/local/go
  - PATH=$PATH:$GOROOT/bin:$GOPATH/bin
script:
  - sudo add-apt-repository ppa:git-core/ppa 1> /dev/null 2> /dev/null
  - sudo apt-get update 1> /dev/null 2> /dev/null
  - sudo apt-get update 1> /dev/null 2> /dev/null
  - sudo apt-get -y install git zip libsqlite3-dev sqlite3 rpm 1> /dev/null 2> /dev/null
  - gem install fpm
  - rbenv rehash
  - make docker
  - make deps
  - make test
  #- make test_postgres
  - make test_mysql
  - make packages
services:
  #- postgres
  - mysql
publish:
  docker:
    branch: upstream-master-with-mods
    docker_port: 4243
    docker_server: {{docker_server}}
    docker_version: 0.10.0
    email: {{docker_email}}
    image_name: clever/drone
    password: {{docker_password}}
    push_latest: false
    registry_login: true
    username: {{docker_username}}
