image: go1.3
git:
  path: github.com/drone/drone
env:
  - GOROOT=/usr/local/go
  - PATH=$PATH:$GOROOT/bin:$GOPATH/bin
script:
  - make deps
  - make
  - make test

notify:
  email:
    recipients:
      - brad@drone.io
